### ISSUE TITLE
[HELP] Next-routes problem?

### ISSUE THREAD

**Issue by guiihlopes** [fridays/next-routes#269] opened 2018-12-21 18:52 UTC
Hello! I'm running latest next version with a typescript environment with a simple next-routes config, but I'm stucked with a problem.

### What's the problem?
I'm running the project, and when I access directly by url `/dashboard/job/create/template/:id`, it works as expected without problem. If I access other page and use the Link component or Router api, my next app just says `[HMR] bundle rebuilding`.

I have inserted a log in next router `routeChangeStart` event and it starts to load the url `/dashboard/job/create/template/:id`, but never ends in `routeChangeComplete` or `routeChangeError` event. 

If I access directly from URL `/dashboard/job/create/template/:id`, go for some component, and back to `/dashboard/job/create/template/:id` using the Link component or Router api, it also work as expected... 

### Here's my route config:

```
module.exports = routes.add(
  'createTemplate',
  '/dashboard/job/create/template/:id',
  'dashboard/job/create/template/create'
)
```

### Here's my page folders:
```
- pages
  - dashboard
    - job
       index
      - create
        - template
          create
          index
....
```

Anyone could help me?

**Comment by guiihlopes** [comment] 2018-12-26 17:49
After a long time trying to find the problem, I just find out that inside the page which was causing problems had a third party component, and dynamic loading it solved my problem

**Comment by zamhaq** [comment] 2019-01-23 20:17
@guiihlopes so your issue was that the browser loaded your page but it never navigated into it? I mean, next would build your page but using client side navigation you were not able to navigate to it but by server side navigation, you could?

**Comment by guiihlopes** [comment] 2019-01-24 15:28
@zamhaq Yes, exactly... With client side navigation it was trying to load the page but for some reason it was not possible to load. Trying to access directly from URL it was loading normally...

Inside the page I was using `react-day-picker`. It was solved when I dynamically loads the component which was importing `react-day-picker`.

I don't know if it's a next-routes problem or just expected... But for sure it's really weird...

**Comment by vaunus** [comment] 2019-02-18 13:14
I am noticing this same issue myself in my development environment. It seems to happen very regularly for me and I can reproduce it quite easily in Chrome. For me it only happens after there has been no interaction with the webpage for a little while. If I then click a page link client-side and I get `[HMR] bundle rebuilding` but the page doesn't load as @guiihlopes described. This also seems to only happen on certain routes.

I noticed @elliottsj is taking over this project (see #244) and after testing his fork with my project it seems that this issue is resolved for me so I've switched over to his package for now until his changes are merged.

**Comment by vaunus** [comment] 2019-02-18 16:50
Ok so one step closer. I don't have time to look at this right now but the issue is caused when idle pages get disposed of by Next.js in dev mode. Once they are disposed of I cannot navigate to them again and just get the `[HMR] bundle rebuilding` and can see the server successfully rebuilds the page, however it doesn't load in the browser.

For example I start on page `A` and navigate to page `B`, `C` and `D` then go back to page `A`. I then wait for about a minute for the server to dispose of some of these pages. Say it disposes of page `B` and `C` but not `D`. I can navigate to page `D` but not to `B` or `C`. If I go back to page `A` and wait some more for page `D` to be disposed I will not be able to navigate to that page either.

**Comment by ntgussoni** [comment] 2019-02-18 20:32
Happening to me too on next@7.0.2 . Clicking on the link does not navigate.

I've narrowed it down to a CSS import im doing on a withCSS next project.

You can try this  component
`react-vertical-timeline-component`

And importing the following is what causes it to not load.
`import "react-vertical-timeline-component/style.min.css";`

**Comment by guiihlopes** [comment] 2019-02-19 01:23
@ntgussoni Probably for me was the css too... I was importing a `.css` in the component which I was using the `react-day-picker`, but I didn't find out that was the css file that was causing the issue... Good catch! Now I think is easier to someone help to improve this problem...

For while... @ntgussoni if you want to solve this problem, load the component which you are importing the css, with dynamic inside the page...

**Comment by ntgussoni** [comment] 2019-02-19 02:40
> @ntgussoni Probably for me was the css too... I was importing a `.css` in the component which I was using the `react-day-picker`, but I didn't find out that was the css file that was causing the issue... Good catch! Now I think is easier to someone help to improve this problem...
> 
> For while... @ntgussoni if you want to solve this problem, load the component which you are importing the css, with dynamic inside the page...

The sollution I found somewhere is to import an empty css in the _app file. Hope it helps

**Comment by vaunus** [comment] 2019-02-19 09:25
Looks like my issue [was an issue with Next.js itself](https://github.com/zeit/next.js/issues/5598). Upgrading to Next.js `8.0.1` solved this for me 😃

**Comment by davegonzalez** [comment] 2019-02-19 19:34
I'm actually running into this with Next.js v8.0.1 with the [React-Slick](https://github.com/akiran/react-slick) package. If I import the css files into the top level page, routing via the `Link` component stops working for that page. Similar to @ntgussoni, I also have withCSS setup in my project, based on the Next.js example.

For now, I've just been working around it by inserting the cdn link into a `<Head>` component.

**Comment by stoberov** [comment] 2019-02-27 23:20
Same issue here - I've got 2 pages, each with its own `import xxxxxxxx.css`. These pages are then linked from the Home page - as long as the CSS import is there, the pages will not load if you tried to navigate from the Home Page. Remove the CSS import, and the problem is "resolved".

**Closed** 2023-02-08 11:23 UTC
